name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checks out the repo
      uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with: 
        username: ${{ ALECTZVETANOV }}
        password: ${{ 12345 }}

    - name: Docker Metadata
      id: meta
      uses: docker/metadata-action@v4
      with: 
        image: alectzvetanov23/tracker-app

    - name: Build and Push Docker images
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
